import Head from "next/head";

import s from "./Admin.module.scss";

export default function Home() {
  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <h2>ADMIN</h2>
      </main>
    </div>
  );
}
