import axios from "axios";
import { GetServerSideProps } from "next";
import Head from "next/head";
import PostPointsCard from "../../src/components/PostPointsCard/PostPointsCard";
import { Drink, Game, Promotion, User } from "../../src/types/model";

import s from "./UserDetail.module.scss";

export default function Home({
  user,
  drinks,
  games,
  promotions,
  userId,
}: {
  user: User;
  drinks: Drink[];
  games: Game[];
  promotions: Promotion[];
  userId: string;
}) {
  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <h2>USER DETAIL</h2>
        <section>
          <article>
            <p>{user.fullName}</p>
            <p>{user.membership.name}</p>
            <p>Puntos: {user.totalPoints}</p>
            <p>Puntos Gastados: {user.totalPointsSpent}</p>
          </article>

          <PostPointsCard drinks={drinks} games={games} userId={userId} />

          <article>
            <p>Promociones Validas:</p>
            {user.membership.promotions.map((promotion) => (
              <p key={promotion.id}>{promotion.name}</p>
            ))}
          </article>
        </section>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const id = context.query.id;

  const userResponse = await axios(`http://localhost:3000/api/user/${id}`);
  const user = userResponse.data;

  const drinksResponse = await axios("http://localhost:3000/api/drink");
  const drinks = drinksResponse.data;

  const gamesResponse = await axios("http://localhost:3000/api/game");
  const games = gamesResponse.data;

  // const promotionsResponse = await axios(
  //   `http://localhost:3000/api/promotions?membership=${user.membership}`
  // );
  // const promotions = promotionsResponse.data;

  return {
    props: {
      user,
      drinks,
      games,
      userId: id,
      // promotions,
    },
  };
};
