import axios from "axios";
import Head from "next/head";
import { GetServerSideProps } from "next";
import { unstable_getServerSession } from "next-auth";
import { authOptions } from "../../api/auth/[...nextauth]";
import { useState } from "react";

//COMPONENTS
import Nav from "../../../src/components/Nav/Nav";
import AdminLayout from "../../../src/components/admin/AdminLayout/AdminLayout";
import Table from "../../../src/components/Ranking/Table/Table";
import ConsumptionRow from "../../../src/components/admin/ConsumptionRow/ConsumptionRow";
import CreateButton from "../../../src/components/admin/CreateButton/CreateButton";

import { Consumption } from "../../../src/types/model";

import s from "./ConsumptionPage.module.scss";
import Modal from "../../../src/components/Modal/Modal";
import CreateConsumption from "../../../src/components/admin/CreateConsumption/CreateConsumption";

type Props = {
  consumptions: {
    drinks: Consumption[];
    games: Consumption[];
  };
};

const trTitles = ["Nombre", "Puntos"];

export default function PromotionPage({ consumptions }: Props) {
  const [openCreateModal, setOpenCreateModal] = useState<boolean>(false);

  return (
    <div className={s.container}>
      <Head>
        <title>Admin - Consumiciones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal
        isOpen={openCreateModal}
        handleCloseModal={() => setOpenCreateModal(false)}
      >
        <CreateConsumption />
      </Modal>

      <Nav />

      <main className={s.main}>
        <AdminLayout>
          <CreateButton
            title="CONSUMICIÓN"
            onClick={() => setOpenCreateModal(true)}
          />
          <div>
            <h4>Bebidas</h4>
            <Table trTitles={trTitles}>
              {consumptions.drinks.map((consumption) => (
                <ConsumptionRow
                  key={consumption.id}
                  consumption={consumption}
                />
              ))}
            </Table>
          </div>

          <div>
            <h4>Juegos</h4>
            <Table trTitles={trTitles}>
              {consumptions.games.map((consumption) => (
                <ConsumptionRow
                  key={consumption.id}
                  consumption={consumption}
                />
              ))}
            </Table>
          </div>
        </AdminLayout>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await unstable_getServerSession(
    context.req,
    context.res,
    authOptions
  );

  if (session?.user.role === "ADMIN") {
    const consumptionsResponse = await axios(
      "http://localhost:3000/api/consumption"
    );
    const consumptions = consumptionsResponse.data;

    return {
      props: {
        consumptions,
      },
    };
  }

  return {
    redirect: {
      destination: "/",
      permanent: false,
    },
  };
};
