import Head from "next/head";
import LoginInput from "../src/components/LoginInpunt/LoginInput";
import Nav from "../src/components/Nav/Nav";

import s from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={s.container}>
      <Head>
        <title>Bar de juegos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className={s.main}>
        <h1>BAR DE JUEGOS</h1>
        <LoginInput />
      </main>

      <footer className={s.footer}></footer>
    </div>
  );
}
