import axios from "axios";
import Head from "next/head";
import { GetServerSideProps } from "next";
import { unstable_getServerSession } from "next-auth";
import { authOptions } from "../../api/auth/[...nextauth]";
import { useState } from "react";
import { useQuery } from "react-query";

//COMPONENTS
import Nav from "../../../src/components/Nav/Nav";
import Table from "../../../src/components/Ranking/Table/Table";
import MembershipRow from "../../../src/components/admin/MembershipRow/MembershipRow";
import AdminLayout from "../../../src/components/admin/AdminLayout/AdminLayout";
import CreateButton from "../../../src/components/admin/CreateButton/CreateButton";
import Modal from "../../../src/components/Modal/Modal";
import CreateMembership from "../../../src/components/admin/CreateMembership/CreateMembership";

import { Membership } from "../../../src/types/model";

import s from "./MembershipPage.module.scss";
import { fetchMemberships } from "../../../src/utils/fetching";

type Props = {
  memberships: Membership[];
};

const trTitles = ["Nombre", "Puntos"];

export default function MembershipPage({ memberships }: Props) {
  const [openCreateModal, setOpenCreateModal] = useState<boolean>(false);

  const [openDeleteModal, setOpenDeleteModal] = useState<boolean>(false);
  const [deleteId, setDeleteId] = useState<string>("");

  const [membershipsList, setMembershipsList] =
    useState<Membership[]>(memberships);

  const handleDeleteMembership = async (membershipId: string) => {
    const { data } = await axios.delete(
      "http://localhost:3000/api/membership",
      { data: { membershipId } }
    );

    if (data.message === "success") {
      console.log("success");
      setMembershipsList(await fetchMemberships());
      setOpenDeleteModal(false);
    }
  };

  return (
    <div className={s.container}>
      <Head>
        <title>Admin - Membresíás</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal
        isOpen={openCreateModal}
        handleCloseModal={() => setOpenCreateModal(false)}
      >
        <CreateMembership
          setMembershipsList={setMembershipsList}
          setOpenCreateModal={setOpenCreateModal}
        />
      </Modal>

      <Modal
        isOpen={openDeleteModal}
        handleCloseModal={() => setOpenDeleteModal(false)}
      >
        <h4>Seguro que quieres eliminar?</h4>
        <button type="button" onClick={() => handleDeleteMembership(deleteId)}>
          ELIMINAR
        </button>
      </Modal>

      <Nav />

      <main className={s.main}>
        <AdminLayout>
          <CreateButton
            title="MEMBRESÍA"
            onClick={() => setOpenCreateModal(true)}
          />
          <div>
            <h4>Membresías</h4>
            <Table trTitles={trTitles}>
              {membershipsList.map((membership) => (
                <MembershipRow
                  key={membership.id}
                  membership={membership}
                  setDeleteId={setDeleteId}
                  setOpenDeleteModal={setOpenDeleteModal}
                />
              ))}
            </Table>
          </div>
        </AdminLayout>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await unstable_getServerSession(
    context.req,
    context.res,
    authOptions
  );

  if (session?.user.role === "ADMIN") {
    const membershipsResponse = await axios(
      "http://localhost:3000/api/membership"
    );
    const memberships = membershipsResponse.data;

    return {
      props: {
        memberships,
      },
    };
  }

  return {
    redirect: {
      destination: "/",
      permanent: false,
    },
  };
};
